#
# config log trace
#

# OpenTracing definitions.
# Implements: http request
open-tracing-sample: "X-B3-Sample"
open-tracing-span-id: "X-B3-Spanid"
open-tracing-trace-id: "X-B3-Traceid"

# ServiceInfo definitions.
service-name: "log-trace"
service-port: 8080
service-version: "1.0"

# log level.
# accepts: off, debug, info, warn, error, fatal
logger-level: debug

# Logger definitions.
logger-name: term

# Trace exporter definitions.
# Accepts: jaeger, zipkin
tracer-name: "jaeger"

# whether to join the log when reporting Trace.
tracer-with-log: true

# Jaeger exporter configurations.
# Follow configurations enabled if tracer-name value is jaeger.
jaeger-trace:
  endpoint: "http://localhost:14268/api/traces"
  username: ""
  password: ""
